[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "langgraph-company-research"
version = "0.1.0"
description = "LangGraph Company Research Agent"
requires-python = ">=3.10"
dependencies = [
    "langchain",
    "langgraph",
    "pydantic",
    "supabase",
    "python-dotenv",
    "langchain-openai",
    "langchain-google-genai",
    "langchain-groq",
    "pandas",
    "pytest",
    "tavily-python"
]
