/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSkillsRouteImport } from './routes/_dashboard/skills'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardPlacementRouteImport } from './routes/_dashboard/placement'
import { Route as DashboardNetworkRouteImport } from './routes/_dashboard/network'
import { Route as DashboardInnovxRouteImport } from './routes/_dashboard/innovx'
import { Route as DashboardHiringRouteImport } from './routes/_dashboard/hiring'
import { Route as DashboardCompaniesRouteImport } from './routes/_dashboard/companies'
import { Route as DashboardCompaniesIndexRouteImport } from './routes/_dashboard/companies.index'
import { Route as DashboardCompaniesIdRouteImport } from './routes/_dashboard/companies.$id'
import { Route as DashboardCompaniesIdSkillsRouteImport } from './routes/_dashboard/companies.$id.skills'
import { Route as DashboardCompaniesIdProcessRouteImport } from './routes/_dashboard/companies.$id.process'
import { Route as DashboardCompaniesIdNetworkRouteImport } from './routes/_dashboard/companies.$id.network'
import { Route as DashboardCompaniesIdInnovxRouteImport } from './routes/_dashboard/companies.$id.innovx'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/_dashboard/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/_dashboard/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlacementRoute = DashboardPlacementRouteImport.update({
  id: '/_dashboard/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNetworkRoute = DashboardNetworkRouteImport.update({
  id: '/_dashboard/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInnovxRoute = DashboardInnovxRouteImport.update({
  id: '/_dashboard/innovx',
  path: '/innovx',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHiringRoute = DashboardHiringRouteImport.update({
  id: '/_dashboard/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/_dashboard/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompaniesIndexRoute = DashboardCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCompaniesRoute,
} as any)
const DashboardCompaniesIdRoute = DashboardCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCompaniesRoute,
} as any)
const DashboardCompaniesIdSkillsRoute =
  DashboardCompaniesIdSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => DashboardCompaniesIdRoute,
  } as any)
const DashboardCompaniesIdProcessRoute =
  DashboardCompaniesIdProcessRouteImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => DashboardCompaniesIdRoute,
  } as any)
const DashboardCompaniesIdNetworkRoute =
  DashboardCompaniesIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => DashboardCompaniesIdRoute,
  } as any)
const DashboardCompaniesIdInnovxRoute =
  DashboardCompaniesIdInnovxRouteImport.update({
    id: '/innovx',
    path: '/innovx',
    getParentRoute: () => DashboardCompaniesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof DashboardCompaniesRouteWithChildren
  '/hiring': typeof DashboardHiringRoute
  '/innovx': typeof DashboardInnovxRoute
  '/network': typeof DashboardNetworkRoute
  '/placement': typeof DashboardPlacementRoute
  '/profile': typeof DashboardProfileRoute
  '/skills': typeof DashboardSkillsRoute
  '/companies/$id': typeof DashboardCompaniesIdRouteWithChildren
  '/companies/': typeof DashboardCompaniesIndexRoute
  '/companies/$id/innovx': typeof DashboardCompaniesIdInnovxRoute
  '/companies/$id/network': typeof DashboardCompaniesIdNetworkRoute
  '/companies/$id/process': typeof DashboardCompaniesIdProcessRoute
  '/companies/$id/skills': typeof DashboardCompaniesIdSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/hiring': typeof DashboardHiringRoute
  '/innovx': typeof DashboardInnovxRoute
  '/network': typeof DashboardNetworkRoute
  '/placement': typeof DashboardPlacementRoute
  '/profile': typeof DashboardProfileRoute
  '/skills': typeof DashboardSkillsRoute
  '/companies/$id': typeof DashboardCompaniesIdRouteWithChildren
  '/companies': typeof DashboardCompaniesIndexRoute
  '/companies/$id/innovx': typeof DashboardCompaniesIdInnovxRoute
  '/companies/$id/network': typeof DashboardCompaniesIdNetworkRoute
  '/companies/$id/process': typeof DashboardCompaniesIdProcessRoute
  '/companies/$id/skills': typeof DashboardCompaniesIdSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/_dashboard/companies': typeof DashboardCompaniesRouteWithChildren
  '/_dashboard/hiring': typeof DashboardHiringRoute
  '/_dashboard/innovx': typeof DashboardInnovxRoute
  '/_dashboard/network': typeof DashboardNetworkRoute
  '/_dashboard/placement': typeof DashboardPlacementRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/skills': typeof DashboardSkillsRoute
  '/_dashboard/companies/$id': typeof DashboardCompaniesIdRouteWithChildren
  '/_dashboard/companies/': typeof DashboardCompaniesIndexRoute
  '/_dashboard/companies/$id/innovx': typeof DashboardCompaniesIdInnovxRoute
  '/_dashboard/companies/$id/network': typeof DashboardCompaniesIdNetworkRoute
  '/_dashboard/companies/$id/process': typeof DashboardCompaniesIdProcessRoute
  '/_dashboard/companies/$id/skills': typeof DashboardCompaniesIdSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/hiring'
    | '/innovx'
    | '/network'
    | '/placement'
    | '/profile'
    | '/skills'
    | '/companies/$id'
    | '/companies/'
    | '/companies/$id/innovx'
    | '/companies/$id/network'
    | '/companies/$id/process'
    | '/companies/$id/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/hiring'
    | '/innovx'
    | '/network'
    | '/placement'
    | '/profile'
    | '/skills'
    | '/companies/$id'
    | '/companies'
    | '/companies/$id/innovx'
    | '/companies/$id/network'
    | '/companies/$id/process'
    | '/companies/$id/skills'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_dashboard/companies'
    | '/_dashboard/hiring'
    | '/_dashboard/innovx'
    | '/_dashboard/network'
    | '/_dashboard/placement'
    | '/_dashboard/profile'
    | '/_dashboard/skills'
    | '/_dashboard/companies/$id'
    | '/_dashboard/companies/'
    | '/_dashboard/companies/$id/innovx'
    | '/_dashboard/companies/$id/network'
    | '/_dashboard/companies/$id/process'
    | '/_dashboard/companies/$id/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardCompaniesRoute: typeof DashboardCompaniesRouteWithChildren
  DashboardHiringRoute: typeof DashboardHiringRoute
  DashboardInnovxRoute: typeof DashboardInnovxRoute
  DashboardNetworkRoute: typeof DashboardNetworkRoute
  DashboardPlacementRoute: typeof DashboardPlacementRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/skills': {
      id: '/_dashboard/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/placement': {
      id: '/_dashboard/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof DashboardPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/network': {
      id: '/_dashboard/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof DashboardNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/innovx': {
      id: '/_dashboard/innovx'
      path: '/innovx'
      fullPath: '/innovx'
      preLoaderRoute: typeof DashboardInnovxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/hiring': {
      id: '/_dashboard/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof DashboardHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/companies': {
      id: '/_dashboard/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/companies/': {
      id: '/_dashboard/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof DashboardCompaniesIndexRouteImport
      parentRoute: typeof DashboardCompaniesRoute
    }
    '/_dashboard/companies/$id': {
      id: '/_dashboard/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof DashboardCompaniesIdRouteImport
      parentRoute: typeof DashboardCompaniesRoute
    }
    '/_dashboard/companies/$id/skills': {
      id: '/_dashboard/companies/$id/skills'
      path: '/skills'
      fullPath: '/companies/$id/skills'
      preLoaderRoute: typeof DashboardCompaniesIdSkillsRouteImport
      parentRoute: typeof DashboardCompaniesIdRoute
    }
    '/_dashboard/companies/$id/process': {
      id: '/_dashboard/companies/$id/process'
      path: '/process'
      fullPath: '/companies/$id/process'
      preLoaderRoute: typeof DashboardCompaniesIdProcessRouteImport
      parentRoute: typeof DashboardCompaniesIdRoute
    }
    '/_dashboard/companies/$id/network': {
      id: '/_dashboard/companies/$id/network'
      path: '/network'
      fullPath: '/companies/$id/network'
      preLoaderRoute: typeof DashboardCompaniesIdNetworkRouteImport
      parentRoute: typeof DashboardCompaniesIdRoute
    }
    '/_dashboard/companies/$id/innovx': {
      id: '/_dashboard/companies/$id/innovx'
      path: '/innovx'
      fullPath: '/companies/$id/innovx'
      preLoaderRoute: typeof DashboardCompaniesIdInnovxRouteImport
      parentRoute: typeof DashboardCompaniesIdRoute
    }
  }
}

interface DashboardCompaniesIdRouteChildren {
  DashboardCompaniesIdInnovxRoute: typeof DashboardCompaniesIdInnovxRoute
  DashboardCompaniesIdNetworkRoute: typeof DashboardCompaniesIdNetworkRoute
  DashboardCompaniesIdProcessRoute: typeof DashboardCompaniesIdProcessRoute
  DashboardCompaniesIdSkillsRoute: typeof DashboardCompaniesIdSkillsRoute
}

const DashboardCompaniesIdRouteChildren: DashboardCompaniesIdRouteChildren = {
  DashboardCompaniesIdInnovxRoute: DashboardCompaniesIdInnovxRoute,
  DashboardCompaniesIdNetworkRoute: DashboardCompaniesIdNetworkRoute,
  DashboardCompaniesIdProcessRoute: DashboardCompaniesIdProcessRoute,
  DashboardCompaniesIdSkillsRoute: DashboardCompaniesIdSkillsRoute,
}

const DashboardCompaniesIdRouteWithChildren =
  DashboardCompaniesIdRoute._addFileChildren(DashboardCompaniesIdRouteChildren)

interface DashboardCompaniesRouteChildren {
  DashboardCompaniesIdRoute: typeof DashboardCompaniesIdRouteWithChildren
  DashboardCompaniesIndexRoute: typeof DashboardCompaniesIndexRoute
}

const DashboardCompaniesRouteChildren: DashboardCompaniesRouteChildren = {
  DashboardCompaniesIdRoute: DashboardCompaniesIdRouteWithChildren,
  DashboardCompaniesIndexRoute: DashboardCompaniesIndexRoute,
}

const DashboardCompaniesRouteWithChildren =
  DashboardCompaniesRoute._addFileChildren(DashboardCompaniesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardCompaniesRoute: DashboardCompaniesRouteWithChildren,
  DashboardHiringRoute: DashboardHiringRoute,
  DashboardInnovxRoute: DashboardInnovxRoute,
  DashboardNetworkRoute: DashboardNetworkRoute,
  DashboardPlacementRoute: DashboardPlacementRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
