"""
Phase 3 — Validation Node (Custom Validation Suite)
=====================================================

Parses the markdown batch files generated by Phase 2 into JSON objects,
then runs each record through the custom validation suite located in ``validation suit 2/``.
Outputs that pass all critical checks are promoted; those that fail are dropped.
"""

import json
import os
import sys
import tempfile
import glob

import pandas as pd
import pytest

# ---------------------------------------------------------------------------
# Resolve project root so imports work regardless of cwd
# ---------------------------------------------------------------------------
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# Also add the validation suite root so its validators/rules resolve
_VALIDATION_SUITE = os.path.abspath(
    os.path.join(_PROJECT_ROOT, "validation suit 2")
)
if _VALIDATION_SUITE not in sys.path:
    sys.path.insert(0, _VALIDATION_SUITE)

from app.models.state import AgentState  # noqa: E402
from app.models.prompt_schema import MAPPED_SCHEMA

# Path to the validation suite test directory
_TESTS_DIR = os.path.join(_VALIDATION_SUITE, "tests")

ID_TO_KEY = {str(val["id"]): key for key, val in MAPPED_SCHEMA.items()}


def parse_markdown_table(content: str) -> dict:
    """Extracts ID and value from a markdown table and maps to schema JSON keys."""
    parsed = {}
    lines = content.splitlines()
    for line in lines:
        line = line.strip()
        if "|" in line:
            parts = [p.strip() for p in line.split("|")]
            # Remove empty strings at start/end if the table is bordered
            if parts and not parts[0]: 
                parts.pop(0)
            if parts and not parts[-1]: 
                parts.pop(-1)
            
            if len(parts) >= 2:
                row_id = parts[0]
                if row_id.isdigit() and row_id in ID_TO_KEY:
                    json_key = ID_TO_KEY[row_id]
                    val = parts[-1]
                    if val.lower() in ("null", "not found", "none"):
                        val = None
                    parsed[json_key] = val
    return parsed


def _run_validation_suite(record: dict) -> dict:
    # Build a single-row DataFrame from the parsed output
    row_df = pd.DataFrame([record])

    # Write to a temporary CSV that the conftest fixture will load
    tmp_dir = os.path.join(_PROJECT_ROOT, "_tmp_validation")
    os.makedirs(tmp_dir, exist_ok=True)
    tmp_csv = os.path.join(tmp_dir, "test_record.csv")
    row_df.to_csv(tmp_csv, index=False)

    # Create a temporary conftest that overrides the data fixture
    tmp_conftest = os.path.join(tmp_dir, "conftest.py")
    conftest_content = f'''
import pytest
import pandas as pd
import os
import sys

# Add validation suite to path
SUITE_ROOT = r"{_VALIDATION_SUITE}"
if SUITE_ROOT not in sys.path:
    sys.path.insert(0, SUITE_ROOT)

DATA_FILE = r"{tmp_csv}"

@pytest.fixture(scope="session")
def company_data():
    return pd.read_csv(DATA_FILE)

@pytest.fixture(scope="session")
def sample_payloads(company_data):
    return company_data.to_dict(orient="records")
'''
    with open(tmp_conftest, "w", encoding="utf-8") as f:
        f.write(conftest_content)

    # Run pytest programmatically
    target_test = os.path.join(_TESTS_DIR, "test_1_input_validation.py")
    exit_code = pytest.main(
        [
            target_test,
            f"-c={tmp_conftest}",
            "--rootdir", tmp_dir,
            "--tb=short",
            "-q",
            "--no-header",
            "-p", "no:cacheprovider",
        ]
    )

    passed = exit_code == 0

    # Clean up temporary files
    try:
        os.remove(tmp_csv)
        os.remove(tmp_conftest)
        os.rmdir(tmp_dir)
    except OSError:
        pass

    return {
        "passed": passed,
        "exit_code": int(exit_code),
    }


def validation_node(state: AgentState) -> dict:
    """Phase 3 node: parse batch files, build JSON records, and validate."""
    validated_outputs = []
    temp_dir = state.get("temp_directory")

    if not temp_dir or not os.path.exists(temp_dir):
        print(f"  [FAIL] Temp directory not found: {temp_dir}")
        return {"validated_outputs": []}

    models = ["mistral", "cerebras", "google"]
    parsed_records = []

    for model_name in models:
        # Find all batch files for this model
        batch_files = glob.glob(os.path.join(temp_dir, f"{model_name}_batch_*.md"))
        if not batch_files:
            continue
            
        full_record = {}
        for b_file in batch_files:
            with open(b_file, "r", encoding="utf-8") as f:
                content = f.read()
                parsed = parse_markdown_table(content)
                full_record.update(parsed)
                
        # Ensure it has exactly 163 keys, filling missing with None
        for key in MAPPED_SCHEMA.keys():
            if key not in full_record:
                full_record[key] = None
                
        full_record["_source_model"] = model_name
        parsed_records.append(full_record)

    for idx, clean_record in enumerate(parsed_records):
        try:
            print(f"\n  --- Validating Output {idx + 1} ---")
            result = _run_validation_suite(clean_record)

            if result["passed"]:
                validated_outputs.append(clean_record)
                print(f"  [PASS] Output {idx + 1} passed validation suite.")
            else:
                print(
                    f"  [FAIL] Output {idx + 1} dropped "
                    f"(pytest exit code: {result['exit_code']})."
                )

        except Exception as e:
            print(f"  [ERROR] Output {idx + 1} skipped — {type(e).__name__}: {e}")
            continue

    print(
        f"\n  Phase 3 summary: {len(validated_outputs)}/{len(parsed_records)} "
        f"outputs passed validation.\n"
    )

    return {"validated_outputs": validated_outputs}
