"""
Mapping of 163 parameters to their execution batches and search tools.
Batches: 1 (Identity), 2 (Market), 3 (Tech), 4 (People), 5 (Growth), 6 (Ops).
Tools: 'Google', 'Tavily', 'GitHub'.
"""

PARAMETER_MAPPING = {
    # BATCH 1: IDENTITY (Basic Info)
    "name": {"batch": 1, "tool": "Google"},
    "short_name": {"batch": 1, "tool": "Google"},
    "logo_url": {"batch": 1, "tool": "Google"},
    "category": {"batch": 1, "tool": "Google"},
    "incorporation_year": {"batch": 1, "tool": "Google"},
    "overview_text": {"batch": 1, "tool": "Tavily"},
    "nature_of_company": {"batch": 1, "tool": "Tavily"},
    "headquarters_address": {"batch": 1, "tool": "Google"},
    "operating_countries": {"batch": 1, "tool": "Google"},
    "office_count": {"batch": 1, "tool": "Google"},
    "office_locations": {"batch": 1, "tool": "Google"},
    "vision_statement": {"batch": 1, "tool": "Tavily"},
    "mission_statement": {"batch": 1, "tool": "Tavily"},
    "core_values": {"batch": 1, "tool": "Tavily"},
    "history_timeline": {"batch": 1, "tool": "Tavily"},
    "recent_news": {"batch": 1, "tool": "Google"},
    "website_url": {"batch": 1, "tool": "Google"},
    "linkedin_url": {"batch": 1, "tool": "Google"},
    "twitter_handle": {"batch": 1, "tool": "Google"},
    "facebook_url": {"batch": 1, "tool": "Google"},
    "instagram_url": {"batch": 1, "tool": "Google"},
    "primary_contact_email": {"batch": 1, "tool": "Google"},
    "primary_phone_number": {"batch": 1, "tool": "Google"},
    "marketing_video_url": {"batch": 1, "tool": "Google"},
    "customer_testimonials": {"batch": 1, "tool": "Tavily"},
    "website_quality": {"batch": 1, "tool": "Tavily"},
    "website_rating": {"batch": 1, "tool": "Google"},
    "website_traffic_rank": {"batch": 1, "tool": "Google"},
    "social_media_followers": {"batch": 1, "tool": "Google"},

    # BATCH 2: MARKET (Customers, Competitors, Strategy)
    "pain_points_addressed": {"batch": 2, "tool": "Tavily"},
    "focus_sectors": {"batch": 2, "tool": "Google"},
    "offerings_description": {"batch": 2, "tool": "Tavily"},
    "top_customers": {"batch": 2, "tool": "Google"},
    "core_value_proposition": {"batch": 2, "tool": "Tavily"},
    "unique_differentiators": {"batch": 2, "tool": "Tavily"},
    "competitive_advantages": {"batch": 2, "tool": "Tavily"},
    "weaknesses_gaps": {"batch": 2, "tool": "Tavily"},
    "key_challenges_needs": {"batch": 2, "tool": "Tavily"},
    "key_competitors": {"batch": 2, "tool": "Google"},
    "market_share_percentage": {"batch": 2, "tool": "Google"},
    "sales_motion": {"batch": 2, "tool": "Tavily"},
    "customer_concentration_risk": {"batch": 2, "tool": "Tavily"},
    "exit_strategy_history": {"batch": 2, "tool": "Tavily"},
    "benchmark_vs_peers": {"batch": 2, "tool": "Tavily"},
    "future_projections": {"batch": 2, "tool": "Tavily"},
    "strategic_priorities": {"batch": 2, "tool": "Tavily"},
    "industry_associations": {"batch": 2, "tool": "Google"},
    "case_studies": {"batch": 2, "tool": "Tavily"},
    "go_to_market_strategy": {"batch": 2, "tool": "Tavily"},
    "innovation_roadmap": {"batch": 2, "tool": "Tavily"},
    "product_pipeline": {"batch": 2, "tool": "Tavily"},
    "tam": {"batch": 2, "tool": "Google"},
    "sam": {"batch": 2, "tool": "Google"},
    "som": {"batch": 2, "tool": "Google"},
    "brand_sentiment_score": {"batch": 2, "tool": "Tavily"},
    "brand_value": {"batch": 2, "tool": "Google"},
    "client_quality": {"batch": 2, "tool": "Tavily"},
    "external_recognition": {"batch": 2, "tool": "Google"},

    # BATCH 3: TECH (Exclusively GitHub Search)
    "technology_partners": {"batch": 3, "tool": "GitHub"},
    "intellectual_property": {"batch": 3, "tool": "GitHub"},
    "r_and_d_investment": {"batch": 3, "tool": "GitHub"},
    "ai_ml_adoption_level": {"batch": 3, "tool": "GitHub"},
    "tech_stack": {"batch": 3, "tool": "GitHub"},
    "cybersecurity_posture": {"batch": 3, "tool": "GitHub"},
    "partnership_ecosystem": {"batch": 3, "tool": "GitHub"},
    "tech_adoption_rating": {"batch": 3, "tool": "GitHub"},
    "automation_level": {"batch": 3, "tool": "GitHub"},
    "tools_access": {"batch": 3, "tool": "GitHub"},
    "skill_relevance": {"batch": 3, "tool": "GitHub"},

    # BATCH 4: PEOPLE (HR, Culture, Employees)
    "employee_size": {"batch": 4, "tool": "Google"},
    "glassdoor_rating": {"batch": 4, "tool": "Google"},
    "indeed_rating": {"batch": 4, "tool": "Google"},
    "google_rating": {"batch": 4, "tool": "Google"},
    "leave_policy": {"batch": 4, "tool": "Tavily"},
    "health_support": {"batch": 4, "tool": "Tavily"},
    "fixed_vs_variable_pay": {"batch": 4, "tool": "Tavily"},
    "bonus_predictability": {"batch": 4, "tool": "Tavily"},
    "esops_incentives": {"batch": 4, "tool": "Tavily"},
    "family_health_insurance": {"batch": 4, "tool": "Tavily"},
    "relocation_support": {"batch": 4, "tool": "Tavily"},
    "lifestyle_benefits": {"batch": 4, "tool": "Tavily"},
    "hiring_velocity": {"batch": 4, "tool": "Tavily"},
    "employee_turnover": {"batch": 4, "tool": "Tavily"},
    "avg_retention_tenure": {"batch": 4, "tool": "Google"},
    "diversity_metrics": {"batch": 4, "tool": "Google"},
    "work_culture_summary": {"batch": 4, "tool": "Tavily"},
    "manager_quality": {"batch": 4, "tool": "Tavily"},
    "psychological_safety": {"batch": 4, "tool": "Tavily"},
    "feedback_culture": {"batch": 4, "tool": "Tavily"},
    "diversity_inclusion_score": {"batch": 4, "tool": "Google"},
    "ethical_standards": {"batch": 4, "tool": "Tavily"},
    "burnout_risk": {"batch": 4, "tool": "Tavily"},
    "layoff_history": {"batch": 4, "tool": "Google"},
    "training_spend": {"batch": 4, "tool": "Tavily"},
    "onboarding_quality": {"batch": 4, "tool": "Tavily"},
    "learning_culture": {"batch": 4, "tool": "Tavily"},
    "exposure_quality": {"batch": 4, "tool": "Tavily"},
    "mentorship_availability": {"batch": 4, "tool": "Tavily"},
    "internal_mobility": {"batch": 4, "tool": "Tavily"},
    "promotion_clarity": {"batch": 4, "tool": "Tavily"},
    "role_clarity": {"batch": 4, "tool": "Tavily"},
    "early_ownership": {"batch": 4, "tool": "Tavily"},
    "work_impact": {"batch": 4, "tool": "Tavily"},
    "execution_thinking_balance": {"batch": 4, "tool": "Tavily"},
    "cross_functional_exposure": {"batch": 4, "tool": "Tavily"},
    "exit_opportunities": {"batch": 4, "tool": "Tavily"},
    "network_strength": {"batch": 4, "tool": "Tavily"},
    "global_exposure": {"batch": 4, "tool": "Tavily"},

    # BATCH 5: GROWTH (Financials, Revenue, Capital)
    "annual_revenue": {"batch": 5, "tool": "Google"},
    "annual_profit": {"batch": 5, "tool": "Google"},
    "revenue_mix": {"batch": 5, "tool": "Tavily"},
    "valuation": {"batch": 5, "tool": "Google"},
    "yoy_growth_rate": {"batch": 5, "tool": "Google"},
    "profitability_status": {"batch": 5, "tool": "Google"},
    "key_investors": {"batch": 5, "tool": "Google"},
    "recent_funding_rounds": {"batch": 5, "tool": "Google"},
    "total_capital_raised": {"batch": 5, "tool": "Google"},
    "customer_acquisition_cost": {"batch": 5, "tool": "Tavily"},
    "customer_lifetime_value": {"batch": 5, "tool": "Tavily"},
    "cac_ltv_ratio": {"batch": 5, "tool": "Tavily"},
    "churn_rate": {"batch": 5, "tool": "Google"},
    "net_promoter_score": {"batch": 5, "tool": "Google"},
    "burn_rate": {"batch": 5, "tool": "Tavily"},
    "runway_months": {"batch": 5, "tool": "Tavily"},
    "burn_multiplier": {"batch": 5, "tool": "Tavily"},
    "company_maturity": {"batch": 5, "tool": "Tavily"},

    # BATCH 6: OPS (Operations, Legal, ESG, Leadership)
    "regulatory_status": {"batch": 6, "tool": "Tavily"},
    "legal_issues": {"batch": 6, "tool": "Tavily"},
    "esg_ratings": {"batch": 6, "tool": "Google"},
    "supply_chain_dependencies": {"batch": 6, "tool": "Tavily"},
    "geopolitical_risks": {"batch": 6, "tool": "Tavily"},
    "macro_risks": {"batch": 6, "tool": "Tavily"},
    "carbon_footprint": {"batch": 6, "tool": "Google"},
    "ethical_sourcing": {"batch": 6, "tool": "Tavily"},
    "awards_recognitions": {"batch": 6, "tool": "Google"},
    "event_participation": {"batch": 6, "tool": "Google"},
    "mission_clarity": {"batch": 6, "tool": "Tavily"},
    "sustainability_csr": {"batch": 6, "tool": "Tavily"},
    "crisis_behavior": {"batch": 6, "tool": "Tavily"},
    "remote_policy_details": {"batch": 6, "tool": "Tavily"},
    "typical_hours": {"batch": 6, "tool": "Tavily"},
    "overtime_expectations": {"batch": 6, "tool": "Tavily"},
    "weekend_work": {"batch": 6, "tool": "Tavily"},
    "flexibility_level": {"batch": 6, "tool": "Tavily"},
    "location_centrality": {"batch": 6, "tool": "Tavily"},
    "public_transport_access": {"batch": 6, "tool": "Tavily"},
    "cab_policy": {"batch": 6, "tool": "Tavily"},
    "airport_commute_time": {"batch": 6, "tool": "Tavily"},
    "office_zone_type": {"batch": 6, "tool": "Tavily"},
    "area_safety": {"batch": 6, "tool": "Tavily"},
    "safety_policies": {"batch": 6, "tool": "Tavily"},
    "infrastructure_safety": {"batch": 6, "tool": "Tavily"},
    "emergency_preparedness": {"batch": 6, "tool": "Tavily"},
    "ceo_name": {"batch": 6, "tool": "Google"},
    "ceo_linkedin_url": {"batch": 6, "tool": "Google"},
    "key_leaders": {"batch": 6, "tool": "Google"},
    "warm_intro_pathways": {"batch": 6, "tool": "Tavily"},
    "decision_maker_access": {"batch": 6, "tool": "Tavily"},
    "contact_person_name": {"batch": 6, "tool": "Google"},
    "contact_person_title": {"batch": 6, "tool": "Google"},
    "contact_person_email": {"batch": 6, "tool": "Google"},
    "contact_person_phone": {"batch": 6, "tool": "Google"},
    "board_members": {"batch": 6, "tool": "Google"},
}
